#!/usr/bin/env python3
"""Public compatibility exports and script entrypoint for the Terra Invicta parser.

Domain implementations live in ti_parser_* modules. Import this facade for
backward-compatible function names; patch dependencies in their owning modules.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from dataclasses import dataclass
from datetime import (
    datetime,
    timedelta,
)
from pathlib import Path
from types import MappingProxyType
from typing import (
    Any,
    Iterable,
)

import ti_parser_hab as hab_layer
import ti_parser_income as income_layer
import ti_parser_nation_projection as nation_projection_layer
import ti_parser_org as org_layer
import ti_parser_ship as ship_layer
import ti_parser_snapshot as snapshot_layer
from ti_parser_ai import calculate_ai_fleet_diagnostics
from ti_parser_catalogs import (
    CatalogIntegrityError,
    RuntimeCatalogs,
    UnsupportedCatalogScenarioError,
    load_runtime_catalogs,
    resolve_required_definition,
)
from ti_parser_claims import calculate_nation_claims
from ti_parser_commands import (
    command_advise,
    command_ai_fleet_diagnostics,
    command_catalog_verify,
    command_councilor,
    command_export,
    command_faction,
    command_hab_plan,
    command_hab_slots,
    command_hab_ui,
    command_nation,
    command_nation_claims,
    command_nation_projection,
    command_nation_ui,
    command_org_plan,
    command_project_analysis,
    command_raw,
    command_research,
    command_research_plan,
    command_research_ui,
    command_ship_plan,
    command_summary,
    command_topbar,
    command_types,
    command_world_ui,
    parse_key_list,
    raw_entry_matches,
)
from ti_parser_config import (
    AEROSOL_TEMPERATURE_DIVISOR,
    ASTRONOMICAL_UNIT_KM,
    BASIC_SPACE_RESOURCES,
    CH4_RELATIVE_IMPACT,
    COUNCILOR_ATTRIBUTES,
    COUNCILOR_INCOME_FIELDS,
    CP_MAINTENANCE_CAMPAIGN_START_GDP_FACTOR,
    DAYS_PER_YEAR,
    DEFAULT_CP_MAINTENANCE_GDP_SCALE,
    DEFAULT_GLOBAL_CONFIG,
    DEFAULT_MAX_COUNCILOR_ATTRIBUTE,
    DEFAULT_SCENARIO_RULES,
    FACTION_IDEOLOGY_BY_TEMPLATE,
    FACTION_RESOURCES,
    GRAVITATIONAL_CONSTANT,
    HAB_ADMIN_ADVISER_RESOURCES,
    HAB_CONFIG,
    HAB_EFFICIENCY_RESOURCES,
    HAB_INCOME_FIELDS,
    HAB_LEO_PRIORITY_RULES,
    HAB_MONTHLY_RESOURCES,
    HAB_PLAN_FOCUS_CHOICES,
    HAB_PLAN_TECH_BONUS_CATEGORIES,
    HAB_SITE_PRODUCTION_FIELDS,
    HAB_SUPPORT_FIELDS,
    INCOME_CONFIG,
    MAX_SOLAR_POWER_MULTIPLIER,
    MINING_BONUS_CONTEXTS,
    MIN_POPULATION_FOR_ADDITIONAL_ARMIES_PER_MILLIONS,
    MIN_POPULATION_FOR_FIRST_ARMY_MILLIONS,
    N2O_RELATIVE_IMPACT,
    NATION_CONDITION_FIELDS,
    NATION_INACTIVE_PRIORITY_KEYS,
    NATION_PRIORITY_ROWS,
    ORG_ATTRIBUTE_FIELDS,
    ORG_PLAN_COST_FIELDS,
    ORG_PLAN_FOCUS_CHOICES,
    ORG_PLAN_SCORE_ATTRIBUTES,
    PRIORITY_BONUS_EFFECT_CONTEXTS,
    PRIORITY_BONUS_ORG_FIELDS,
    PROJECT_ANALYSIS_MODULE_SAMPLE_COUNTS,
    PROJECT_ANALYSIS_SORT_CHOICES,
    RESEARCH_PLAN_MODE_CHOICES,
    RESEARCH_PLAN_SCORE_AXES,
    SAFE_GREENHOUSE_GAS_LEVELS,
    SCENARIO_RULE_OVERRIDES,
    SCHEMA_VERSION,
    SHIP_PLAN_ROLE_CHOICES,
    SHIP_PLAN_SHIPYARD_TIERS,
    SHIP_PLAN_UTILITY_TEMPLATE_FILES,
    SHIP_PLAN_WEAPON_TEMPLATE_FILES,
    SNAPSHOT_CONFIG,
    STANDARD_GRAVITY_MPS2,
    ScenarioRules,
    TEMPERATURE_ANOMALY_FACTOR,
    TOPBAR_EFFECT_CONTEXTS,
    TOPBAR_RESOURCES,
    WORLD_MARKET_RESOURCES,
    WORLD_SELLABLE_MARKET_RESOURCES,
)
from ti_parser_core import (
    CalculationDependency,
    CalculationDependencyError,
    DEFAULT_CACHE_DIR,
    IndexedState,
    LocationCatalogError,
    SAVE_GLOB,
    SolarPowerDataError,
    TemplateSource,
    apply_effect_modifiers,
    as_float,
    build_index,
    cache_key,
    campaign_code,
    candidate_save_dirs,
    candidate_templates_dirs,
    clean_number,
    clean_numbers,
    effect_modifier_delta,
    faction_effect_contexts,
    faction_is_human_player,
    file_fingerprint,
    find_faction_state,
    find_latest_save,
    first_value,
    json_default,
    load_hab_module_catalog,
    load_location_catalog,
    load_named_templates,
    load_save,
    load_trait_templates,
    location_catalog_diagnostics,
    match_raw_state,
    module_catalog_diagnostics,
    print_json,
    raw_name_values,
    raw_state_id,
    ref_id,
    ref_summary,
    region_nation_summary,
    resolve_ref,
    resolve_save_path,
    resolve_scenario_templates,
    resolve_templates_dir,
    save_fingerprint,
    scenario_template_name,
    short_type,
    snapshot_fingerprint,
    state_value_by_id,
    template_source_value,
    type_entries,
)
from ti_parser_hab_construction import (
    candidate_module_monthly_delta,
    completion_datetime,
    faction_has_helium3_access,
    faction_stockpile,
    hab_body_is_colonized,
    hab_body_is_inhabited,
    hab_body_is_irradiated,
    hab_body_site_states,
    hab_core_completion_minimum_days,
    hab_irradiated_multiplier,
    hab_module_build_materials,
    hab_module_construction_analysis,
    hab_module_mass_tons,
    hab_planned_empty_slots,
    hab_projected_power_summary,
    hab_upgrade_info,
    hypothetical_completed_module_record,
    module_affordable_with_materials,
    module_affordable_with_template_weights,
    module_break_even_analysis,
    module_build_cost_map,
    module_has_economic_planning_value,
    module_is_relevant_to_hab_type,
    module_one_per_hab_conflict_names,
    module_unmet_requirements,
    monthly_delta_market_equivalent,
    resource_cost_market_equivalent,
    resource_market_purchase_values,
    resource_scarcity_weights,
)
from ti_parser_hab_plan import (
    add_monthly_delta,
    annotate_candidate_opportunity_costs,
    calculate_hab_plan,
    candidate_affordable,
    candidate_focus_score,
    hab_module_candidate_rows,
    hab_module_upgrade_rows,
    hab_plan_row,
    module_balanced_score,
    module_candidate_row,
    module_category_bonus_score,
    module_project_score,
    module_research_score,
    module_resource_score,
    monthly_delta_times,
    opportunity_cost_baseline,
    opportunity_cost_for_score,
    opportunity_costs_for_candidate,
    payback_candidates,
    power_candidates,
    sorted_candidates,
    suggested_fill_entry,
    suggested_hab_fill,
    tech_bonus_map_for_template,
)
from ti_parser_hab_ui import (
    calculate_hab_slots,
    calculate_hab_ui,
    hab_barycenter_state,
    hab_construction_surface_body,
    hab_control_point_capacity,
    hab_leo_priority_bonuses,
    hab_location_summary,
    hab_module_construction_time_modifier,
    hab_module_power,
    hab_natural_solar_multiplier,
    hab_power_summary,
    hab_research_and_mc,
    hab_solar_mirror_bonus,
    hab_tech_bonuses,
    lagrange_solar_visibility,
    natural_space_object_sun_distance_au,
    orbit_template_semi_major_axis_km,
    raise_solar_power_data_error,
    require_solar_body_template,
    solar_hab_label,
    space_body_atmosphere_solar_modifier,
    space_body_drag_velocity_penalty_kps,
    space_body_local_escape_velocity_mps,
    space_body_max_radius_km,
    space_body_mean_radius_km,
    space_body_orbit_solar_visibility,
    space_body_relative_energy_for_mining,
    space_body_semi_major_axis_km,
    space_body_surface_solar_visibility,
    space_body_template,
    summarize_hab_slots,
    validate_hab_solar_context,
)
from ti_parser_mechanics import Rules
from ti_parser_nation_ui import (
    _nation_ui_control_point_weights,
    _nation_ui_priority_validity,
    calculate_nation_ui,
    cohesion_label,
    democracy_label,
    display_one_decimal,
    display_public_opinion,
    education_label,
    federation_space_program,
    first_control_point,
    inequality_label,
    int_round,
    miltech_label,
    nation_army_details,
    nation_priority_rows,
    unrest_label,
)
from ti_parser_nation_validity import (
    MIN_CONTROL_POINTS_FOR_NAVY,
    MIN_CONTROL_POINTS_FOR_NAVY_EXCEPTION,
    PCGDP_FOR_NAVY_EXCEPTION,
    PriorityValidityResult,
    can_build_navy,
    evaluate_priority_validity,
)
from ti_parser_project_analysis import (
    active_project_names,
    active_slots_with_hypothetical_project_category,
    bottleneck_penalty_from_delta,
    calculate_project_analysis,
    default_project_analysis_slot,
    hypothetical_project_category_modifier,
    hypothetical_project_points_to_slot,
    module_count_sample,
    module_static_analysis,
    module_template_static_monthly_delta,
    project_analysis_candidate_names,
    project_analysis_flags,
    project_candidate_analysis,
    project_candidate_status,
    project_finished_faction_view,
    project_module_aggregate,
    project_progress_entries_by_name,
    project_ranking_brief,
    project_resource_grant_map,
    project_unlocked_module_templates,
    prospective_module_unlocks_for_project,
    resource_bottlenecks,
    resource_grant_score,
)
from ti_parser_projection_adapter import (
    _projection_dependency_error,
    _region_occupation_fraction,
    _required_projection_army_type,
    _required_projection_bool,
    _required_projection_catalog_row,
    _required_projection_deployment_type,
    _required_projection_list,
    _required_projection_mapping,
    _required_projection_number,
    _required_projection_ocean_type,
    _required_projection_string,
    _serialized_numeric_tracker,
    calculate_nation_projection,
    extract_nation_projection_state,
    faction_effect_expirations_for_projection,
    faction_priority_bonuses_for_projection,
    projection_advisor_mission_schedule,
    projection_advisor_profiles,
)
from ti_parser_research import (
    ResearchTemplates,
    active_faction_councilors,
    active_slots_with_category,
    calculate_research_breakdown,
    calculate_research_ui,
    diminishing_research_modifier,
    distributed_category_modifier,
    eta_from_daily,
    faction_base_research_daily,
    faction_category_modifier_components,
    faction_fleet_category_modifier,
    faction_fraction_weight_in_slot,
    faction_hab_category_modifier,
    faction_investigations_modifier,
    faction_org_category_modifier,
    faction_project_allowed,
    faction_project_slots,
    faction_research_cache_key,
    faction_research_weights,
    faction_total_research_weights,
    faction_trait_category_modifier,
    fleet_in_earth_system,
    global_research_contributions,
    load_research_templates,
    multiple_facilities_multiplier,
    project_facility_counts,
    project_progress_by_slot,
    project_template_cost,
    research_distribution,
    research_points_to_slot,
    research_progress_row,
    tech_bonus_sum,
    tech_template_cost,
    template_display,
)
from ti_parser_research_plan import (
    active_global_research_names,
    active_project_research_names,
    available_global_research_templates,
    available_project_research_templates,
    calculate_research_plan,
    direct_unlocks_for_template,
    finished_global_research_names,
    project_progress_records_by_template,
    research_plan_candidate_row,
    research_plan_category_context,
    research_plan_goal_views,
    research_plan_keyword_tags,
    research_plan_reference_weight_fraction,
    research_plan_resource_grant_maps,
    research_plan_shortlist,
    research_template_effects,
    research_template_prereqs,
    research_template_resources_granted,
    score_research_plan_candidates,
    string_list,
)
from ti_parser_runtime import (
    MAX_ORGS_PER_COUNCILOR,
    active_modules_in_sectors,
    active_owned_control_points,
    active_scenario_rules,
    apply_conditional_attribute_mods,
    average,
    build_snapshot,
    calculate_org_plan,
    calculation_catalogs,
    clamp_attribute,
    compare_condition,
    condition_eval_unknown,
    condition_nation_summary,
    control_point_summary,
    councilor_attribute_breakdown,
    councilor_is_income_active,
    councilor_monthly_income,
    councilor_org_plan_profile,
    councilor_research_and_mc,
    councilor_resource_income,
    councilor_summary_maps,
    councilor_yearly_income,
    current_save_datetime,
    evaluate_condition,
    evaluate_councilor_conditionals,
    extant_nation_states,
    faction_active_org_mining_bonus,
    faction_brief,
    faction_councilor_ids,
    faction_display_from_ref,
    faction_hab_states,
    faction_ideology_key,
    faction_is_active_human,
    faction_is_player,
    faction_key_from_ref,
    faction_mining_multiplier,
    faction_mining_rate,
    faction_public_opinion,
    faction_sector_states,
    faction_ship_designs,
    faction_ship_states,
    find_faction_for_councilor,
    get_effective_module_state,
    global_summary,
    hab_administration_modifier,
    hab_core_module_record,
    hab_crew,
    hab_farm_crew_discount,
    hab_module_active_record,
    hab_module_counts,
    hab_module_current_mission_control,
    hab_module_empty,
    hab_module_functional,
    hab_module_okay,
    hab_module_projected_mission_control,
    hab_module_records,
    hab_monthly_resource_income,
    hab_sector_states,
    hab_site_daily_production,
    hab_slot_summary,
    hab_slot_usable,
    hab_template_crew_support,
    hab_template_direct_support,
    hab_template_income,
    hab_template_special_rules,
    hab_template_support,
    human_faction_entries,
    int_like,
    load_or_build_snapshot,
    match_named,
    metadata_summary,
    module_is_active,
    nation_adviser_science_bonus,
    nation_allowed_armies,
    nation_boost_contribution_month,
    nation_can_have_navy,
    nation_control_points,
    nation_current_boost_year,
    nation_current_mission_control,
    nation_federation_pooled_year,
    nation_financial_sector_owned,
    nation_has_owned_knowledge_sector,
    nation_influence_contribution_month,
    nation_mission_control_contribution,
    nation_money_contribution_month,
    nation_monthly_research,
    nation_non_colony_unoccupied_region_count,
    nation_population_millions,
    nation_raw_boost_year,
    nation_research_contribution_month,
    national_ip_multiplier,
    org_acquisition_cost,
    org_attribute_mods,
    org_attribute_values,
    org_plan_attribute_delta,
    org_plan_best_assignment,
    org_plan_candidate_row,
    org_plan_committee_score,
    org_plan_committee_totals,
    org_plan_controlled_nation_ids,
    org_plan_cost_affordable,
    org_plan_councilor_faction,
    org_plan_faction_eligibility,
    org_plan_final_attributes,
    org_plan_major_attributes,
    org_plan_nation_interest,
    org_plan_normalize_focus,
    org_plan_objective_score,
    org_plan_org_row,
    org_plan_owner_eligibility,
    org_plan_region_nation_id,
    org_plan_requirement_summary,
    org_plan_roster_summary,
    org_plan_state_key,
    parse_bool,
    parse_modifier_number,
    required_catalog_row,
    research_speed_modifier,
    scenario_customizations,
    scenario_float,
    search_org_committee_plan,
    stat_mod_entry,
    state_adviser_attribute_bonus,
    sum_attr_mods,
    summarize_councilors,
    summarize_faction,
    summarize_fleets,
    summarize_nation,
    summarize_regions,
    ti_datetime,
    time_summary,
    trait_attribute_mods,
    trait_mod_has_condition,
)
from ti_parser_ship import (
    SHIP_PLAN_MOUNT_SLOTS,
    SHIP_PLAN_SELF_POWERED_DRIVE_CLASSES,
    ship_plan_add_scaled_materials,
    ship_plan_armor_mass_tons,
    ship_plan_clean_resources,
    ship_plan_compatible_power_plants,
    ship_plan_drive_goal_views,
    ship_plan_drive_open_cycle,
    ship_plan_drive_power_requirement_gw,
    ship_plan_drive_row,
    ship_plan_drive_thrust_power_gw,
    ship_plan_generic_row,
    ship_plan_hull_row,
    ship_plan_materials,
    ship_plan_part_unlocked,
    ship_plan_power_plant_class_compatible,
    ship_plan_power_plant_row,
    ship_plan_utility_role_tags,
    ship_plan_utility_row,
    ship_plan_utility_rule_value,
    ship_plan_weapon_cost,
    ship_plan_weapon_energy_gj,
    ship_plan_weapon_goal_views,
    ship_plan_weapon_mass_tons,
    ship_plan_weapon_row,
)
from ti_parser_ship_plan import (
    calculate_ship_plan,
    ship_plan_existing_designs,
    ship_plan_select_design,
    ship_plan_shipyard_times,
    ship_plan_simulation_catalogs,
    simulate_ship_design,
)
from ti_parser_snapshot import SnapshotConfig
from ti_parser_topbar import (
    calculate_topbar,
    control_point_maintenance_gdp_scale,
    faction_control_point_maintenance,
    faction_excess_mission_control_yearly_income,
    faction_hab_resource_at_date,
    faction_max_mission_control_components,
    faction_mining_calculation_samples,
    faction_negative_yearly_income_from_unassigned_orgs,
    faction_queued_mission_control_changes,
    faction_resource_components_yearly,
    faction_yearly_income_from_councilors,
    faction_yearly_income_from_diplomacy,
    faction_yearly_income_from_habs,
    faction_yearly_income_from_nations,
    faction_yearly_income_from_ships,
    first_sustained_surplus_date,
    forecast_faction_hab_resource,
    mission_control_available_for_planning,
    nation_control_point_maintenance_cost,
)
from ti_parser_verify import verify_catalogs
from ti_parser_world import (
    calculate_global_public_opinion,
    calculate_world_atrocities,
    calculate_world_ui,
    calculate_world_wars,
    hab_is_alien,
    mean_annual_gdp_damage,
    nation_army_count,
    nation_brief_from_state,
    nation_executive_faction,
    nation_naval_score,
    temperature_anomaly_components,
    war_alliance_states,
    war_side_summary,
    world_environment,
    world_global_data,
    world_resource_market,
    world_space_population,
)


def build_parser() -> argparse.ArgumentParser:
    from ti_parser_cli import build_parser as build_cli_parser

    return build_cli_parser(sys.modules[__name__])


def main(argv: list[str] | None = None) -> int:
    from ti_parser_cli import main as cli_main

    return cli_main(sys.modules[__name__], argv)


if __name__ == "__main__":
    raise SystemExit(main())
